### ISSUE TITLE
Unable to start zookeeper in Ubuntu 16/18 when installed from repositories.

### ISSUE THREAD

**Issue by ignatovich-artem** [lean-delivery/ansible-role-zookeeper#16]
##### SUMMARY

Unable to start zookeeper in Ubuntu 16/18 when installed from repositories.
After service is started it exits immediately without errors, no child processes spawned.
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.7.12
```

##### OS / ENVIRONMENT

Ubuntu 16, Ubuntu 18

**Comment by tgadiev** [comment]
Fixed by https://github.com/lean-delivery/ansible-role-zookeeper/pull/18
